### ISSUE TITLE
My profile

### ISSUE THREAD

**Issue by Mariann98** [tomimarkus991/Its-Doggo-Time#20]
- update ja sign out buttonid peaksid mitte kumama
- Username võiks sama suur olla kastis kus on email ja password
- käpajälg võiks veidi suurem olla
- update the photo võiks äkki olla beeziga kirjutatud -> kui selle peal hoverid kas see saaks siis vajadusel kas helebeez või hele mustjashall olla, hetkel nagu helesinine

**Comment by tomimarkus991** [comment]
- [x] update ja sign out buttonid peaksid mitte kumama
- [x] Username võiks sama suur olla kastis kus on email ja password
- [x] käpajälg võiks veidi suurem olla
- [x] update the photo võiks äkki olla beeziga kirjutatud -> kui selle peal hoverid kas see saaks siis vajadusel kas helebeez või hele mustjashall olla, hetkel nagu helesinine
