### ISSUE TITLE
my groups

### ISSUE THREAD

**Issue by Mariann98** [tomimarkus991/Its-Doggo-Time#21]
- kui grupp on lisatud ja käpajälg (KJ) kõrval siis võiks see KJ olla prportsioonis pildiga
- ja vb peaks selle kasti veidi ümber tegema, sest ülevalt see nagu on sujuvalt valge ja siis allpool alles näha et kast seal
- KJ väiksem mis on üleval paremal
- "new doggo group" avanedes peab seal olema BACK nupp ja vahed paremaks. Vb nimi kui kirjutad võiks keskel olla
- my groups -> isabella/thor grupp - see edit button võiks kaunim olla :D plus siis see õige add nupp paremale kasti äärde

**Comment by tomimarkus991** [comment]
_ja vb peaks selle kasti veidi ümber tegema, sest ülevalt see nagu on sujuvalt valge ja siis allpool alles näha et kast seal_

jep see on Chakra UI-ga seotud, tuleb custom box teha selle jaoks

**Comment by Mariann98** [comment]
kui vajutad edit nuppu isabellal nt, siis see linnuke on kandiliselt, aga peaks ümar olema :D

**Comment by tomimarkus991** [comment]
I agree with those changes. 👍 
They are now implemented and will come with the next update.
