### ISSUE TITLE
opening page - log in or sign up

### ISSUE THREAD

**Issue by Mariann98** [tomimarkus991/Its-Doggo-Time#22]
- võtaks selle pisema koera ülevalt paremalt maha, kaks tk ei sobi ikka.
- teksti osas peab veelm mõtlema :D
- opening page-> sign up/in - selle githubi ma võtaks isiklukult maha, sest enamik seda ei kasuta ju.....või kasutab? :D
- opening page -> sign up - " already have an account? Sign in " see sign in on vist üks space liiast. sama kõib sign in'i lehel.

**Comment by tomimarkus991** [comment]
_võtaks selle pisema koera ülevalt paremalt maha, kaks tk ei sobi ikka_
ei sobi aga selle äravõtmine on pain in the 🦋
edit:
Found a fix for it.
- [x] võtaks selle pisema koera ülevalt paremalt maha, kaks tk ei sobi ikka.
- [x] opening page -> sign up - " already have an account? Sign in " see sign in on vist üks space liiast. sama kõib sign in'i lehel.

_opening page-> sign up/in - selle githubi ma võtaks isiklukult maha, sest enamik seda ei kasuta ju.....või kasutab? :D_
peab githubi ka promotima ja see seda koledamaks ei tee

**Comment by Mariann98** [comment]
kui on pain in da butterfly siis ei ole nii karm :)
